// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DomainClass.Common;
using System;
using System.Collections.Generic;

namespace DomainClass.Models;

public partial class Gewichtsklassen : BaseEntity
{
    public int GewichtsKlassenId { get; set; }

    public short AklassenId { get; set; }

    public short Gewicht { get; set; }

    public bool? Gepoolt { get; set; }
}