// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DomainClass.Common;
using System;
using System.Collections.Generic;

namespace DomainClass.Models;

public class Altersklassen : BaseEntity
{
    public int AklassenId { get; set; }

    public string AklassenName { get; set; }

    public string Gewichtsklassen { get; set; }

    public string Stilart { get; set; }
}