// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DomainClass.Models;

public partial class Altersklassen
{
    public int AklassenId { get; set; }

    public string AklassenName { get; set; }

    public string Gewichtsklassen { get; set; }

    public string Stilart { get; set; }
}