// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DomainClass.Models;

public partial class Verbaende
{
    public string LandesVerband { get; set; }

    public string Verbandsname { get; set; }

    public Guid? VerbandsGuid { get; set; }

    public string InternetAdresse { get; set; }

    public string Email { get; set; }

    public string Info { get; set; }
}