// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DomainClass.Models;

public partial class Vereine
{
    public int VereinsNr { get; set; }

    public string Landesverband { get; set; }

    public string Bezirk { get; set; }

    public string VereinBez { get; set; }
}